//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisDAL.NetGsm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms/", ConfigurationName="NetGsm.smsnn")]
    public interface smsnn {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsRequest", ReplyAction="http://sms/smsnn/gelensmsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.gelensmsResponse gelensms(ServisDAL.NetGsm.gelensmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsRequest", ReplyAction="http://sms/smsnn/gelensmsResponse")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.gelensmsResponse> gelensmsAsync(ServisDAL.NetGsm.gelensmsRequest request);
        
        // CODEGEN: Generating message contract since message part namespace (SMS) does not match the default value (http://sms/)
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_nnRequest", ReplyAction="http://sms/smsnn/sms_gonder_nnResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.sms_gonder_nnResponse sms_gonder_nn(ServisDAL.NetGsm.sms_gonder_nnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_nnRequest", ReplyAction="http://sms/smsnn/sms_gonder_nnResponse")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.sms_gonder_nnResponse> sms_gonder_nnAsync(ServisDAL.NetGsm.sms_gonder_nnRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_1nRequest", ReplyAction="http://sms/smsnn/sms_gonder_1nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.sms_gonder_1nResponse sms_gonder_1n(ServisDAL.NetGsm.sms_gonder_1nRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_1nRequest", ReplyAction="http://sms/smsnn/sms_gonder_1nResponse")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.sms_gonder_1nResponse> sms_gonder_1nAsync(ServisDAL.NetGsm.sms_gonder_1nRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/krediRequest", ReplyAction="http://sms/smsnn/krediResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.krediResponse kredi(ServisDAL.NetGsm.krediRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/krediRequest", ReplyAction="http://sms/smsnn/krediResponse")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.krediResponse> krediAsync(ServisDAL.NetGsm.krediRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/paketkampanyaRequest", ReplyAction="http://sms/smsnn/paketkampanyaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.paketkampanyaResponse paketkampanya(ServisDAL.NetGsm.paketkampanyaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/paketkampanyaRequest", ReplyAction="http://sms/smsnn/paketkampanyaResponse")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.paketkampanyaResponse> paketkampanyaAsync(ServisDAL.NetGsm.paketkampanyaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporRequest", ReplyAction="http://sms/smsnn/raporResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.raporResponse rapor(ServisDAL.NetGsm.raporRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporRequest", ReplyAction="http://sms/smsnn/raporResponse")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.raporResponse> raporAsync(ServisDAL.NetGsm.raporRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/rapor_v2Request", ReplyAction="http://sms/smsnn/rapor_v2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.rapor_v2Response rapor_v2(ServisDAL.NetGsm.rapor_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/rapor_v2Request", ReplyAction="http://sms/smsnn/rapor_v2Response")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.rapor_v2Response> rapor_v2Async(ServisDAL.NetGsm.rapor_v2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gondericiadlariRequest", ReplyAction="http://sms/smsnn/gondericiadlariResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServisDAL.NetGsm.gondericiadlariResponse gondericiadlari(ServisDAL.NetGsm.gondericiadlariRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gondericiadlariRequest", ReplyAction="http://sms/smsnn/gondericiadlariResponse")]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.gondericiadlariResponse> gondericiadlariAsync(ServisDAL.NetGsm.gondericiadlariRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensms", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gelensmsRequest() {
        }
        
        public gelensmsRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gelensmsResponse() {
        }
        
        public gelensmsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nn", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        public sms_gonder_nnRequest() {
        }
        
        public sms_gonder_nnRequest(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate) {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nnResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="SMS")]
        public string @return;
        
        public sms_gonder_nnResponse() {
        }
        
        public sms_gonder_nnResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1n", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        public sms_gonder_1nRequest() {
        }
        
        public sms_gonder_1nRequest(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate) {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1nResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sms_gonder_1nResponse() {
        }
        
        public sms_gonder_1nResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kredi", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public krediRequest() {
        }
        
        public krediRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="krediResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public krediResponse() {
        }
        
        public krediResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanya", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public paketkampanyaRequest() {
        }
        
        public paketkampanyaRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanyaResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public paketkampanyaResponse() {
        }
        
        public paketkampanyaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        public raporRequest() {
        }
        
        public raporRequest(string username, string password, string bulkid, int status, int version) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public raporResponse() {
        }
        
        public raporResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("telno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] telno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detail;
        
        public rapor_v2Request() {
        }
        
        public rapor_v2Request(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
            this.telno = telno;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public rapor_v2Response() {
        }
        
        public rapor_v2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlari", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gondericiadlariRequest() {
        }
        
        public gondericiadlariRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlariResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gondericiadlariResponse() {
        }
        
        public gondericiadlariResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsnnChannel : ServisDAL.NetGsm.smsnn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsnnClient : System.ServiceModel.ClientBase<ServisDAL.NetGsm.smsnn>, ServisDAL.NetGsm.smsnn {
        
        public smsnnClient() {
        }
        
        public smsnnClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsnnClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsnnClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsnnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.gelensmsResponse ServisDAL.NetGsm.smsnn.gelensms(ServisDAL.NetGsm.gelensmsRequest request) {
            return base.Channel.gelensms(request);
        }
        
        public string gelensms(string username, string password) {
            ServisDAL.NetGsm.gelensmsRequest inValue = new ServisDAL.NetGsm.gelensmsRequest();
            inValue.username = username;
            inValue.password = password;
            ServisDAL.NetGsm.gelensmsResponse retVal = ((ServisDAL.NetGsm.smsnn)(this)).gelensms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.gelensmsResponse> ServisDAL.NetGsm.smsnn.gelensmsAsync(ServisDAL.NetGsm.gelensmsRequest request) {
            return base.Channel.gelensmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.gelensmsResponse> gelensmsAsync(string username, string password) {
            ServisDAL.NetGsm.gelensmsRequest inValue = new ServisDAL.NetGsm.gelensmsRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ServisDAL.NetGsm.smsnn)(this)).gelensmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.sms_gonder_nnResponse ServisDAL.NetGsm.smsnn.sms_gonder_nn(ServisDAL.NetGsm.sms_gonder_nnRequest request) {
            return base.Channel.sms_gonder_nn(request);
        }
        
        public string sms_gonder_nn(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate) {
            ServisDAL.NetGsm.sms_gonder_nnRequest inValue = new ServisDAL.NetGsm.sms_gonder_nnRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            ServisDAL.NetGsm.sms_gonder_nnResponse retVal = ((ServisDAL.NetGsm.smsnn)(this)).sms_gonder_nn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.sms_gonder_nnResponse> ServisDAL.NetGsm.smsnn.sms_gonder_nnAsync(ServisDAL.NetGsm.sms_gonder_nnRequest request) {
            return base.Channel.sms_gonder_nnAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.sms_gonder_nnResponse> sms_gonder_nnAsync(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate) {
            ServisDAL.NetGsm.sms_gonder_nnRequest inValue = new ServisDAL.NetGsm.sms_gonder_nnRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            return ((ServisDAL.NetGsm.smsnn)(this)).sms_gonder_nnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.sms_gonder_1nResponse ServisDAL.NetGsm.smsnn.sms_gonder_1n(ServisDAL.NetGsm.sms_gonder_1nRequest request) {
            return base.Channel.sms_gonder_1n(request);
        }
        
        public string sms_gonder_1n(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate) {
            ServisDAL.NetGsm.sms_gonder_1nRequest inValue = new ServisDAL.NetGsm.sms_gonder_1nRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            ServisDAL.NetGsm.sms_gonder_1nResponse retVal = ((ServisDAL.NetGsm.smsnn)(this)).sms_gonder_1n(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.sms_gonder_1nResponse> ServisDAL.NetGsm.smsnn.sms_gonder_1nAsync(ServisDAL.NetGsm.sms_gonder_1nRequest request) {
            return base.Channel.sms_gonder_1nAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.sms_gonder_1nResponse> sms_gonder_1nAsync(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate) {
            ServisDAL.NetGsm.sms_gonder_1nRequest inValue = new ServisDAL.NetGsm.sms_gonder_1nRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            return ((ServisDAL.NetGsm.smsnn)(this)).sms_gonder_1nAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.krediResponse ServisDAL.NetGsm.smsnn.kredi(ServisDAL.NetGsm.krediRequest request) {
            return base.Channel.kredi(request);
        }
        
        public string kredi(string username, string password) {
            ServisDAL.NetGsm.krediRequest inValue = new ServisDAL.NetGsm.krediRequest();
            inValue.username = username;
            inValue.password = password;
            ServisDAL.NetGsm.krediResponse retVal = ((ServisDAL.NetGsm.smsnn)(this)).kredi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.krediResponse> ServisDAL.NetGsm.smsnn.krediAsync(ServisDAL.NetGsm.krediRequest request) {
            return base.Channel.krediAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.krediResponse> krediAsync(string username, string password) {
            ServisDAL.NetGsm.krediRequest inValue = new ServisDAL.NetGsm.krediRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ServisDAL.NetGsm.smsnn)(this)).krediAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.paketkampanyaResponse ServisDAL.NetGsm.smsnn.paketkampanya(ServisDAL.NetGsm.paketkampanyaRequest request) {
            return base.Channel.paketkampanya(request);
        }
        
        public string paketkampanya(string username, string password) {
            ServisDAL.NetGsm.paketkampanyaRequest inValue = new ServisDAL.NetGsm.paketkampanyaRequest();
            inValue.username = username;
            inValue.password = password;
            ServisDAL.NetGsm.paketkampanyaResponse retVal = ((ServisDAL.NetGsm.smsnn)(this)).paketkampanya(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.paketkampanyaResponse> ServisDAL.NetGsm.smsnn.paketkampanyaAsync(ServisDAL.NetGsm.paketkampanyaRequest request) {
            return base.Channel.paketkampanyaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.paketkampanyaResponse> paketkampanyaAsync(string username, string password) {
            ServisDAL.NetGsm.paketkampanyaRequest inValue = new ServisDAL.NetGsm.paketkampanyaRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ServisDAL.NetGsm.smsnn)(this)).paketkampanyaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.raporResponse ServisDAL.NetGsm.smsnn.rapor(ServisDAL.NetGsm.raporRequest request) {
            return base.Channel.rapor(request);
        }
        
        public string rapor(string username, string password, string bulkid, int status, int version) {
            ServisDAL.NetGsm.raporRequest inValue = new ServisDAL.NetGsm.raporRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            ServisDAL.NetGsm.raporResponse retVal = ((ServisDAL.NetGsm.smsnn)(this)).rapor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.raporResponse> ServisDAL.NetGsm.smsnn.raporAsync(ServisDAL.NetGsm.raporRequest request) {
            return base.Channel.raporAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.raporResponse> raporAsync(string username, string password, string bulkid, int status, int version) {
            ServisDAL.NetGsm.raporRequest inValue = new ServisDAL.NetGsm.raporRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            return ((ServisDAL.NetGsm.smsnn)(this)).raporAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.rapor_v2Response ServisDAL.NetGsm.smsnn.rapor_v2(ServisDAL.NetGsm.rapor_v2Request request) {
            return base.Channel.rapor_v2(request);
        }
        
        public string rapor_v2(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            ServisDAL.NetGsm.rapor_v2Request inValue = new ServisDAL.NetGsm.rapor_v2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            inValue.telno = telno;
            inValue.detail = detail;
            ServisDAL.NetGsm.rapor_v2Response retVal = ((ServisDAL.NetGsm.smsnn)(this)).rapor_v2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.rapor_v2Response> ServisDAL.NetGsm.smsnn.rapor_v2Async(ServisDAL.NetGsm.rapor_v2Request request) {
            return base.Channel.rapor_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.rapor_v2Response> rapor_v2Async(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            ServisDAL.NetGsm.rapor_v2Request inValue = new ServisDAL.NetGsm.rapor_v2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            inValue.telno = telno;
            inValue.detail = detail;
            return ((ServisDAL.NetGsm.smsnn)(this)).rapor_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServisDAL.NetGsm.gondericiadlariResponse ServisDAL.NetGsm.smsnn.gondericiadlari(ServisDAL.NetGsm.gondericiadlariRequest request) {
            return base.Channel.gondericiadlari(request);
        }
        
        public string gondericiadlari(string username, string password) {
            ServisDAL.NetGsm.gondericiadlariRequest inValue = new ServisDAL.NetGsm.gondericiadlariRequest();
            inValue.username = username;
            inValue.password = password;
            ServisDAL.NetGsm.gondericiadlariResponse retVal = ((ServisDAL.NetGsm.smsnn)(this)).gondericiadlari(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServisDAL.NetGsm.gondericiadlariResponse> ServisDAL.NetGsm.smsnn.gondericiadlariAsync(ServisDAL.NetGsm.gondericiadlariRequest request) {
            return base.Channel.gondericiadlariAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServisDAL.NetGsm.gondericiadlariResponse> gondericiadlariAsync(string username, string password) {
            ServisDAL.NetGsm.gondericiadlariRequest inValue = new ServisDAL.NetGsm.gondericiadlariRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ServisDAL.NetGsm.smsnn)(this)).gondericiadlariAsync(inValue);
        }
    }
}
