//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonelik_pakets
    {
        public abonelik_pakets()
        {
            this.faturas = new HashSet<fatura>();
            this.customers = new HashSet<customer>();
        }
    
        public int paket_id { get; set; }
        public string paket_adi { get; set; }
        public int gun { get; set; }
        public decimal fiyat { get; set; }
        public Nullable<bool> iptal { get; set; }
    
        public virtual ICollection<fatura> faturas { get; set; }
        public virtual ICollection<customer> customers { get; set; }
    }
}
