//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayar
    {
        public int Ayar_ID { get; set; }
        public string Mail_Server { get; set; }
        public int Mail_Port { get; set; }
        public string Mail_UserName { get; set; }
        public string Mail_PW { get; set; }
        public string Mail_Kimden { get; set; }
        public string aktif_adres { get; set; }
        public string tur { get; set; }
        public string Firma { get; set; }
        public string gonderen { get; set; }
    }
}
