//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class carihesap
    {
        public int MusteriID { get; set; }
        public decimal ToplamBorc { get; set; }
        public decimal ToplamOdenen { get; set; }
        public decimal NetBorc { get; set; }
        public decimal ToplamAlacak { get; set; }
        public decimal ToplamOdedigimiz { get; set; }
        public decimal NetAlacak { get; set; }
        public decimal ToplamBakiye { get; set; }
        public string Firma { get; set; }
        public string kullanici { get; set; }
        public Nullable<System.DateTime> son_mesaj { get; set; }
        public string telefon { get; set; }
        public string adi { get; set; }
    }
}
