//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class cihaz
    {
        public cihaz()
        {
            this.alim_detays = new HashSet<alim_detays>();
            this.cihaz_fifos = new HashSet<cihaz_fifos>();
            this.cihaz_garantis = new HashSet<cihaz_garantis>();
            this.cihaz_stoks = new HashSet<cihaz_stoks>();
            this.satislars = new HashSet<satislar>();
            this.servis_paket_detays = new HashSet<servis_paket_detays>();
            this.servicehesaps = new HashSet<servicehesap>();
        }
    
        public int ID { get; set; }
        public string cihaz_adi { get; set; }
        public string aciklama { get; set; }
        public string seri_no { get; set; }
        public int garanti_suresi { get; set; }
        public string Firma { get; set; }
        public int grupid { get; set; }
        public string barkod { get; set; }
    
        public virtual ICollection<alim_detays> alim_detays { get; set; }
        public virtual ICollection<cihaz_fifos> cihaz_fifos { get; set; }
        public virtual ICollection<cihaz_garantis> cihaz_garantis { get; set; }
        public virtual ICollection<cihaz_stoks> cihaz_stoks { get; set; }
        public virtual ICollection<satislar> satislars { get; set; }
        public virtual ICollection<servis_paket_detays> servis_paket_detays { get; set; }
        public virtual ICollection<servicehesap> servicehesaps { get; set; }
        public virtual cihaz_grups cihaz_grups { get; set; }
    }
}
