//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class cihaz_fifos
    {
        public int id { get; set; }
        public int cihaz_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public decimal giris { get; set; }
        public decimal cikis { get; set; }
        public decimal bakiye { get; set; }
        public decimal fiyat { get; set; }
        public bool iptal { get; set; }
    
        public virtual cihaz cihaz { get; set; }
    }
}
