//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.alims = new HashSet<alim>();
            this.cekhesaps = new HashSet<cekhesap>();
            this.cihaz_garantis = new HashSet<cihaz_garantis>();
            this.kart_hesaps = new HashSet<kart_hesaps>();
            this.kasaharekets = new HashSet<kasahareket>();
            this.satislars = new HashSet<satislar>();
            this.musteriodemelers = new HashSet<musteriodemeler>();
            this.poshesaps = new HashSet<poshesap>();
            this.service_faturas = new HashSet<service_faturas>();
            this.servicehesaps = new HashSet<servicehesap>();
            this.servicehesaps1 = new HashSet<servicehesap>();
            this.services = new HashSet<service>();
            this.services1 = new HashSet<service>();
            this.faturas = new HashSet<fatura>();
            this.uruns = new HashSet<urun>();
            this.yedek_uruns = new HashSet<yedek_uruns>();
            this.faturas1 = new HashSet<fatura>();
        }
    
        public int CustID { get; set; }
        public string Ad { get; set; }
        public string TC { get; set; }
        public string Adres { get; set; }
        public string telefon { get; set; }
        public string telefon_cep { get; set; }
        public string email { get; set; }
        public string tanimlayici { get; set; }
        public string Firma { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<bool> pasif { get; set; }
        public string istihbarat { get; set; }
        public Nullable<decimal> prim_yekun { get; set; }
        public Nullable<decimal> prim_kar { get; set; }
        public Nullable<bool> musteri { get; set; }
        public Nullable<bool> tedarikci { get; set; }
        public Nullable<bool> usta { get; set; }
        public Nullable<bool> disservis { get; set; }
        public string unvan { get; set; }
        public string vd { get; set; }
        public Nullable<int> paket_id { get; set; }
        public Nullable<System.DateTime> expire { get; set; }
        public Nullable<int> antenid { get; set; }
    
        public virtual ICollection<alim> alims { get; set; }
        public virtual ICollection<cekhesap> cekhesaps { get; set; }
        public virtual ICollection<cihaz_garantis> cihaz_garantis { get; set; }
        public virtual ICollection<kart_hesaps> kart_hesaps { get; set; }
        public virtual ICollection<kasahareket> kasaharekets { get; set; }
        public virtual ICollection<satislar> satislars { get; set; }
        public virtual ICollection<musteriodemeler> musteriodemelers { get; set; }
        public virtual ICollection<poshesap> poshesaps { get; set; }
        public virtual ICollection<service_faturas> service_faturas { get; set; }
        public virtual ICollection<servicehesap> servicehesaps { get; set; }
        public virtual ICollection<servicehesap> servicehesaps1 { get; set; }
        public virtual ICollection<service> services { get; set; }
        public virtual ICollection<service> services1 { get; set; }
        public virtual ICollection<fatura> faturas { get; set; }
        public virtual ICollection<urun> uruns { get; set; }
        public virtual ICollection<yedek_uruns> yedek_uruns { get; set; }
        public virtual abonelik_pakets abonelik_pakets { get; set; }
        public virtual ICollection<fatura> faturas1 { get; set; }
        public virtual anten anten { get; set; }
    }
}
