//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatura
    {
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string no { get; set; }
        public int taksit_no { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> sattis_tarih { get; set; }
        public string tc { get; set; }
        public string ad { get; set; }
        public string adres { get; set; }
        public decimal tutar { get; set; }
        public Nullable<decimal> tamirci_maliyet { get; set; }
        public string telefon { get; set; }
        public decimal odenen { get; set; }
        public decimal bakiye { get; set; }
        public decimal vergisiz_tutar { get; set; }
        public decimal KDV { get; set; }
        public decimal OIV { get; set; }
        public string fat_seri { get; set; }
        public Nullable<int> fat_no { get; set; }
        public Nullable<System.DateTime> basim_tarih { get; set; }
        public Nullable<bool> odendi { get; set; }
        public string tur { get; set; }
        public string tahsilat_turu { get; set; }
        public bool iptal { get; set; }
        public Nullable<int> hesap_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public string tahsilat_aciklama { get; set; }
        public Nullable<int> taksit_sayisi { get; set; }
        public string belge_no { get; set; }
        public Nullable<System.DateTime> vade_tarih { get; set; }
        public Nullable<decimal> masraf { get; set; }
        public Nullable<int> borc_odeme_id { get; set; }
        public Nullable<bool> mahsup { get; set; }
        public string mahsup_key { get; set; }
        public Nullable<int> iade_id { get; set; }
        public Nullable<int> servicehesap_id { get; set; }
        public System.DateTime son_odeme_tarihi { get; set; }
        public Nullable<System.DateTime> odeme_tarihi { get; set; }
        public Nullable<System.DateTime> islem_tarihi { get; set; }
        public Nullable<System.DateTime> guncelleme_tarihi { get; set; }
        public string islemci_user { get; set; }
        public Nullable<int> satis_id { get; set; }
        public Nullable<int> tamirci_id { get; set; }
        public string inserted { get; set; }
        public string updated { get; set; }
        public string deleted { get; set; }
        public Nullable<int> paket_id { get; set; }
    
        public virtual satislar satislar { get; set; }
        public virtual servicehesap servicehesap { get; set; }
        public virtual customer customer { get; set; }
        public virtual abonelik_pakets abonelik_pakets { get; set; }
        public virtual customer customer1 { get; set; }
    }
}
