//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class kart_caris
    {
        public int kart_id { get; set; }
        public decimal borc { get; set; }
        public decimal odenen { get; set; }
        public decimal bakiye { get; set; }
        public string kart_adi { get; set; }
    
        public virtual kart_tanims kart_tanims { get; set; }
    }
}
