//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_ayars
    {
        public int ID { get; set; }
        public string tur { get; set; }
        public int iliski_id { get; set; }
        public string gonderen { get; set; }
        public string konu { get; set; }
        public string FirmaTam { get; set; }
        public string Adres { get; set; }
        public string url { get; set; }
        public string Telefon { get; set; }
        public string durum { get; set; }
        public string body_mesaj { get; set; }
        public int kritik_gun { get; set; }
        public string resim_yol { get; set; }
        public Nullable<bool> aktif { get; set; }
        public string Firma { get; set; }
    }
}
