//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class manuel
    {
        public int id { get; set; }
        public string unvan { get; set; }
        public decimal tutar { get; set; }
        public decimal kdv { get; set; }
        public decimal otv { get; set; }
        public decimal oiv { get; set; }
        public decimal yekun { get; set; }
        public bool iptal { get; set; }
        public System.DateTime tarih { get; set; }
        public string inserted { get; set; }
        public string updated { get; set; }
        public string deleted { get; set; }
    }
}
