//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class panel
    {
        public int ID { get; set; }
        public int servis_sayisi { get; set; }
        public int onay_bekleyen_sayisi { get; set; }
        public int borclu_sayisi { get; set; }
        public int emanet_sayisi { get; set; }
        public decimal ToplamBorc { get; set; }
        public decimal ToplamOdenen { get; set; }
        public decimal NetBorc { get; set; }
        public decimal ToplamAlacak { get; set; }
        public decimal ToplamOdedigimiz { get; set; }
        public decimal NetAlacak { get; set; }
        public decimal ToplamBakiye { get; set; }
        public int musteri_sayisi { get; set; }
        public string kullanici { get; set; }
        public string Firma { get; set; }
    }
}
