//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class radiusEntities : DbContext
    {
       
       public radiusEntities(DbConnection connectionString, bool contextOwnsConnection = true)
            : base(connectionString, contextOwnsConnection)
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alim_detays> alim_detays { get; set; }
        public virtual DbSet<alim> alims { get; set; }
        public virtual DbSet<ayargenel> ayargenels { get; set; }
        public virtual DbSet<ayar> ayars { get; set; }
        public virtual DbSet<banka> bankas { get; set; }
        public virtual DbSet<carihesap> carihesaps { get; set; }
        public virtual DbSet<cekhesap> cekhesaps { get; set; }
        public virtual DbSet<cihaz_fifos> cihaz_fifos { get; set; }
        public virtual DbSet<cihaz_garantis> cihaz_garantis { get; set; }
        public virtual DbSet<cihaz_stoks> cihaz_stoks { get; set; }
        public virtual DbSet<cihaz> cihazs { get; set; }
        public virtual DbSet<kart_caris> kart_caris { get; set; }
        public virtual DbSet<kart_hesaps> kart_hesaps { get; set; }
        public virtual DbSet<kart_odemes> kart_odemes { get; set; }
        public virtual DbSet<kart_tanims> kart_tanims { get; set; }
        public virtual DbSet<kasahareket> kasaharekets { get; set; }
        public virtual DbSet<kasahesap> kasahesaps { get; set; }
        public virtual DbSet<mail_ayars> mail_ayars { get; set; }
        public virtual DbSet<masraf_tips> masraf_tips { get; set; }
        public virtual DbSet<musteriodemeler> musteriodemelers { get; set; }
        public virtual DbSet<not> nots { get; set; }
        public virtual DbSet<panel> panels { get; set; }
        public virtual DbSet<pos_tanims> pos_tanims { get; set; }
        public virtual DbSet<poshesap> poshesaps { get; set; }
        public virtual DbSet<satislar> satislars { get; set; }
        public virtual DbSet<service_durums> service_durums { get; set; }
        public virtual DbSet<service_faturas> service_faturas { get; set; }
        public virtual DbSet<service_tips> service_tips { get; set; }
        public virtual DbSet<servicedetay> servicedetays { get; set; }
        public virtual DbSet<servicehesap> servicehesaps { get; set; }
        public virtual DbSet<servis_paket_detays> servis_paket_detays { get; set; }
        public virtual DbSet<servis_pakets> servis_pakets { get; set; }
        public virtual DbSet<sms_ayars> sms_ayars { get; set; }
        public virtual DbSet<urun> uruns { get; set; }
        public virtual DbSet<yedek_uruns> yedek_uruns { get; set; }
        public virtual DbSet<fatura> faturas { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<cihaz_grups> cihaz_grups { get; set; }
        public virtual DbSet<manuel> manuels { get; set; }
        public virtual DbSet<abonelik_pakets> abonelik_pakets { get; set; }
        public virtual DbSet<anten> antens { get; set; }
    }
}
