//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicehesap
    {
        public servicehesap()
        {
            this.faturas = new HashSet<fatura>();
        }
    
        public int HesapID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> tamirci_id { get; set; }
        public int ServiceID { get; set; }
        public string servis_kimlik { get; set; }
        public string IslemParca { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public decimal Yekun { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime TarihZaman { get; set; }
        public int adet { get; set; }
        public Nullable<int> cihaz_id { get; set; }
        public string cihaz_adi { get; set; }
        public Nullable<int> cihaz_gsure { get; set; }
        public string Urun_Cinsi { get; set; }
        public Nullable<System.DateTime> Urun_GarantiBaslangic { get; set; }
        public Nullable<System.DateTime> Urun_GarantiBitis { get; set; }
        public Nullable<int> Urun_GarantiSuresi { get; set; }
        public string Urun_Aciklama { get; set; }
        public string Urun_Kimlik { get; set; }
        public bool onay { get; set; }
        public Nullable<System.DateTime> Onay_tarih { get; set; }
        public Nullable<int> stok_id { get; set; }
        public Nullable<decimal> birim_maliyet { get; set; }
        public Nullable<decimal> toplam_maliyet { get; set; }
        public bool iptal { get; set; }
        public string Firma { get; set; }
        public string kullanici { get; set; }
        public string inserted { get; set; }
        public string updated { get; set; }
        public string deleted { get; set; }
    
        public virtual cihaz cihaz { get; set; }
        public virtual ICollection<fatura> faturas { get; set; }
        public virtual service service { get; set; }
        public virtual customer customer { get; set; }
        public virtual customer customer1 { get; set; }
    }
}
