//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_durums
    {
        public service_durums()
        {
            this.servicedetays = new HashSet<servicedetay>();
        }
    
        public int Durum_ID { get; set; }
        public string Durum { get; set; }
        public bool SMS { get; set; }
        public bool Mail { get; set; }
        public bool Whatsapp { get; set; }
        public Nullable<bool> baslangicmi { get; set; }
        public Nullable<bool> sonmu { get; set; }
        public Nullable<bool> kararmi { get; set; }
        public Nullable<bool> onaymi { get; set; }
        public Nullable<bool> iptal { get; set; }
        public string Firma { get; set; }
        public string Mail_Tema { get; set; }
    
        public virtual ICollection<servicedetay> servicedetays { get; set; }
    }
}
