//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class servis_pakets
    {
        public servis_pakets()
        {
            this.servis_paket_detays = new HashSet<servis_paket_detays>();
        }
    
        public int paket_id { get; set; }
        public string paket_adi { get; set; }
        public decimal tutar { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> iptal { get; set; }
        public string Firma { get; set; }
    
        public virtual ICollection<servis_paket_detays> servis_paket_detays { get; set; }
    }
}
