//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_ayars
    {
        public int ID { get; set; }
        public string tur { get; set; }
        public int iliski_id { get; set; }
        public string gonderen { get; set; }
        public string mesaj { get; set; }
        public Nullable<int> kritik_gun { get; set; }
        public string tip { get; set; }
        public Nullable<bool> aktif { get; set; }
        public string Firma { get; set; }
    }
}
